# Generated by Django 6.0.4 on 2026-04-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReglaAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.IntegerField(choices=[(1, 'Bajo'), (2, 'Medio'), (3, 'Alto')])),
                ('condicion', models.CharField(max_length=200)),
                ('umbral', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Regla de Alerta',
                'verbose_name_plural': 'Reglas de Alerta',
                'db_table': 'reglaalerta',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_generacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('RESUELTA', 'Resuelta'), ('DESCARTADA', 'Descartada')], default='PENDIENTE', max_length=20)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='academico.estudiante')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alertas.reglaalerta')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='BitacoraImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo_reporte', models.CharField(max_length=60)),
                ('total_registros', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('exitoso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Importación',
                'verbose_name_plural': 'Bitácoras de Importación',
                'db_table': 'bitacoraimportacion',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evidencia', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=200, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervenciones', to='alertas.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'db_table': 'intervencion',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('SISTEMA', 'Sistema'), ('WHATSAPP', 'WhatsApp')], max_length=30)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='alertas.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
            },
        ),
    ]
