# Generated by Django 6.0.4 on 2026-04-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('nivel', models.CharField(max_length=30)),
                ('condicion', models.TextField()),
            ],
            options={
                'verbose_name': 'Regla',
                'verbose_name_plural': 'Reglas',
                'db_table': 'regla',
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=30)),
                ('estudiante', models.ForeignKey(db_column='codigo_estudiante', on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alertas.regla')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'alerta',
            },
        ),
        migrations.CreateModel(
            name='BitacoraImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(max_length=50)),
                ('total_registros', models.IntegerField(default=0)),
                ('errores', models.IntegerField(default=0)),
                ('exitoso', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Importación',
                'verbose_name_plural': 'Bitácoras de Importación',
                'db_table': 'bitacora_importacion',
            },
        ),
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('evidencia', models.CharField(blank=True, max_length=300, null=True)),
                ('resultado', models.CharField(blank=True, max_length=100, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'db_table': 'intervencion',
            },
        ),
    ]
