# Generated by Django 6.0.4 on 2026-04-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BitacoraImportacion',
        ),
    ]
