# Generated by Django 6.0.5 on 2026-05-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0002_delete_bitacoraimportacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regla',
            name='condicion',
        ),
        migrations.AddField(
            model_name='regla',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='regla',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regla',
            name='operador',
            field=models.CharField(choices=[('<', 'Menor que'), ('>', 'Mayor que'), ('<=', 'Menor o igual que'), ('>=', 'Mayor o igual que'), ('==', 'Igual que')], default='<', max_length=5),
        ),
        migrations.AddField(
            model_name='regla',
            name='tipo',
            field=models.CharField(choices=[('PROMEDIO', 'Promedio Acumulado'), ('REPROBACION', 'Número de Materias Reprobadas'), ('ATRASO', 'Atraso Curricular')], default='PROMEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='regla',
            name='valor_umbral',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='regla',
            name='nivel',
            field=models.CharField(choices=[('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo')], default='medium', max_length=20),
        ),
    ]
