# Generated by Django 6.0.4 on 2026-05-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0003_remove_regla_condicion_regla_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='tipo',
            field=models.CharField(choices=[('TUTORIA', 'Tutoría'), ('CITACION', 'Citación'), ('REMISION', 'Remisión')], default='TUTORIA', max_length=20),
            preserve_default=False,
        ),
    ]
