# Generated by Django 4.2.30 on 2026-05-09 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0004_intervencion_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_url', models.URLField(max_length=500)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo_archivo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='alertas.intervencion')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'evidencia',
            },
        ),
    ]
