# Generated by Django 4.2.30 on 2026-05-09 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('alertas', '0005_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotacionIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('intervencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anotaciones', to='alertas.intervencion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Anotación',
                'verbose_name_plural': 'Anotaciones',
                'db_table': 'anotacion_intervencion',
                'ordering': ['-fecha'],
            },
        ),
    ]
