# Generated by Django 6.0.4 on 2026-05-14 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_bitacoraimportacion'),
        ('alertas', '0006_anotacionintervencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='prioridad',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RiesgoEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_riesgo', models.CharField(choices=[('high', 'Alto'), ('medium', 'Medio'), ('low', 'Bajo'), ('unknown', 'Sin Dato')], default='unknown', max_length=20)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('reglas_aplicadas', models.JSONField(default=list)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='riesgo', to='academico.estudiante')),
            ],
            options={
                'verbose_name': 'Riesgo Estudiante',
                'verbose_name_plural': 'Riesgos Estudiantes',
                'db_table': 'riesgo_estudiante',
            },
        ),
    ]
