# Generated by Django 6.0.4 on 2026-05-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0007_regla_prioridad_riesgoestudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='valor_causa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
