# Generated by Django 6.0.4 on 2026-05-14 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0008_alerta_valor_causa'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
