# Generated by Django 6.0.4 on 2026-05-16 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0009_alerta_metadata'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinatario', models.CharField(max_length=255)),
                ('rol_destinatario', models.CharField(max_length=50)),
                ('canal', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('INTERNA', 'Notificación Interna')], max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('reintento', 'Pendiente de Reintento')], max_length=20)),
                ('detalle_error', models.TextField(blank=True, null=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_notificaciones', to='alertas.alerta')),
            ],
            options={
                'verbose_name': 'Historial de Notificación',
                'verbose_name_plural': 'Historial de Notificaciones',
                'db_table': 'notificacion_historial',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('alerta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alertas.alerta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_internas', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Notificación Interna',
                'verbose_name_plural': 'Notificaciones Internas',
                'db_table': 'notificacion_interna',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
