# Generated by Django 6.0.4 on 2026-09-30 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0012_riesgoestudianteperiodo'),
        ('usuarios', '0006_merge_20260529_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='EjecucionReevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('MANUAL', 'Manual')], default='PROGRAMADA', max_length=20)),
                ('estado', models.CharField(choices=[('EN_CURSO', 'En curso'), ('EXITOSA', 'Exitosa'), ('PARCIAL', 'Parcial (con errores)'), ('FALLIDA', 'Fallida')], default='EN_CURSO', max_length=20)),
                ('intento', models.PositiveSmallIntegerField(default=1)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('alcance', models.JSONField(blank=True, default=dict)),
                ('total_estudiantes', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('total_errores', models.IntegerField(default=0)),
                ('cambios_riesgo', models.IntegerField(default=0)),
                ('alertas_generadas', models.IntegerField(default=0)),
                ('alertas_actualizadas', models.IntegerField(default=0)),
                ('alertas_cerradas', models.IntegerField(default=0)),
                ('estudiantes_por_nivel', models.JSONField(blank=True, default=dict)),
                ('detalle_cambios', models.JSONField(blank=True, default=list)),
                ('errores', models.JSONField(blank=True, default=list)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ejecución de Re-evaluación',
                'verbose_name_plural': 'Ejecuciones de Re-evaluación',
                'db_table': 'ejecucion_reevaluacion',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='ejecucionreevaluacion',
            name='reintento_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reintentos', to='alertas.ejecucionreevaluacion'),
        ),
        migrations.AddField(
            model_name='ejecucionreevaluacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
    ]
