# Generated by Django 6.0.4 on 2026-10-06 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_asistencia'),
        ('alertas', '0013_ejecucionreevaluacion'),
        ('usuarios', '0008_alter_auditoria_tipo_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('dias_inactividad_alerta', models.PositiveIntegerField(default=7)),
                ('dias_inactividad_intervencion', models.PositiveIntegerField(default=15)),
                ('dias_entre_recordatorios', models.PositiveIntegerField(default=7)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3)),
                ('roles_destinatarios', models.JSONField(blank=True, default=list)),
                ('notificar_responsable', models.BooleanField(default=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('ejecutando_desde', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Recordatorios',
                'verbose_name_plural': 'Configuración de Recordatorios',
                'db_table': 'configuracion_recordatorio',
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_caso', models.CharField(choices=[('ALERTA', 'Alerta sin intervenciones'), ('INTERVENCION', 'Intervención sin seguimiento')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente / en reintento'), ('ENVIADO', 'Enviado'), ('PARCIAL', 'Enviado parcialmente'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('ultima_actividad', models.DateTimeField()),
                ('dias_inactivo', models.PositiveIntegerField(default=0)),
                ('canales', models.JSONField(blank=True, default=dict)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3)),
                ('historial_intentos', models.JSONField(blank=True, default=list)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_cancelacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'db_table': 'recordatorio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='notificacionhistorial',
            name='tipo',
            field=models.CharField(choices=[('ALERTA', 'Alerta generada'), ('RECORDATORIO', 'Recordatorio de seguimiento')], default='ALERTA', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracionrecordatorio',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='alerta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='alertas.alerta'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='destinatario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='usuarios.usuario'),
        ),
        migrations.AddField(
            model_name='recordatorio',
            name='intervencion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='alertas.intervencion'),
        ),
        migrations.AddIndex(
            model_name='recordatorio',
            index=models.Index(fields=['estado'], name='recordatori_estado_a7479d_idx'),
        ),
    ]
