# Generated by Django 6.0.4 on 2026-10-07 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alertas', '0014_recordatorios_seguimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='regla',
            name='parametros',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='regla',
            name='tipo',
            field=models.CharField(choices=[('PROMEDIO', 'Promedio Acumulado'), ('REPROBACION', 'Número de Materias Reprobadas'), ('ATRASO', 'Atraso Curricular'), ('CORTE', 'Alerta por Corte')], default='PROMEDIO', max_length=20),
        ),
    ]
