# Generated by Django 6.0.4 on 2026-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alertas", "0016_crear_reglas_corte_iniciales"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regla",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("PROMEDIO", "Promedio Acumulado"),
                    ("REPROBACION", "Número de Materias Reprobadas"),
                    ("ATRASO", "Atraso Curricular"),
                    ("CORTE", "Alerta por Corte"),
                    ("INASISTENCIA", "Porcentaje de Inasistencia"),
                ],
                default="PROMEDIO",
                max_length=20,
            ),
        ),
    ]
