# Generated by Django 6.0.4 on 2026-10-08 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0010_curso_umbral_inasistencia"),
        ("alertas", "0018_crear_regla_inasistencia"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvisoPreventivoInasistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
                ("umbral", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "destinatario",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("exitoso", "Exitoso"),
                            ("fallido", "Fallido"),
                            ("reintento", "Pendiente de Reintento"),
                            ("sin_correo", "Estudiante sin correo"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("detalle_error", models.TextField(blank=True, null=True)),
                ("fecha_envio", models.DateTimeField(auto_now_add=True)),
                (
                    "curso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.curso",
                    ),
                ),
                (
                    "estudiante",
                    models.ForeignKey(
                        db_column="codigo_estudiante",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.estudiante",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academico.periodo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Aviso preventivo de inasistencia",
                "verbose_name_plural": "Avisos preventivos de inasistencia",
                "db_table": "aviso_preventivo_inasistencia",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("estudiante", "curso", "periodo"),
                        name="aviso_inasistencia_unico",
                    )
                ],
            },
        ),
    ]
