# Generated by Django 6.0.4 on 2026-05-23 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(default='DOCENTE', max_length=150),
        ),
    ]
