# Generated by Django 6.0.4 on 2026-05-27 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('DOCENTE', 'Docente'), ('DIRECTOR', 'Director'), ('BIENESTAR', 'Bienestar'), ('ADMINISTRADOR', 'Administrador')], max_length=20),
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo_accion', models.CharField(choices=[('CREAR_USUARIO', 'Crear Usuario'), ('EDITAR_ROL', 'Editar Rol de Usuario'), ('DESACTIVAR_USUARIO', 'Desactivar Usuario'), ('IMPORTACION', 'Importación de Datos'), ('CREAR_REGLA', 'Crear Regla'), ('MODIFICAR_REGLA', 'Modificar Regla'), ('DESACTIVAR_REGLA', 'Desactivar Regla'), ('CERRAR_ALERTA', 'Cerrar Alerta'), ('REGISTRAR_INTERVENCION', 'Registrar Intervención'), ('ACCESO_DENEGADO', 'Acceso Denegado (403)')], max_length=50)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
