# Generated by Django 6.0.4 on 2026-05-29 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_0002_alter_usuario_rol_0003_alter_auditoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_accion',
            field=models.CharField(choices=[('CREAR_USUARIO', 'Crear Usuario'), ('EDITAR_ROL', 'Editar Rol de Usuario'), ('DESACTIVAR_USUARIO', 'Desactivar Usuario'), ('IMPORTACION', 'Importación de Datos'), ('CREAR_REGLA', 'Crear Regla'), ('MODIFICAR_REGLA', 'Modificar Regla'), ('ACTIVAR_REGLA', 'Activar Regla'), ('DESACTIVAR_REGLA', 'Desactivar Regla'), ('CERRAR_ALERTA', 'Cerrar Alerta'), ('REGISTRAR_INTERVENCION', 'Registrar Intervención'), ('CONCLUIR_INTERVENCION', 'Concluir Intervención'), ('GENERAR_ALERTAS', 'Generar Alertas'), ('LOGIN', 'Inicio de Sesión'), ('ACCESO_DENEGADO', 'Acceso Denegado (403)')], max_length=50),
        ),
    ]
