# Generated by Django 6.0.4 on 2026-05-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_merge_0002_alter_usuario_rol_0003_alter_auditoria_tipo_accion'),
        ('usuarios', '0005_alter_auditoria_tipo_accion'),
    ]

    operations = [
    ]
