# Generated by Django 6.0.4 on 2026-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_hashear_contrasenas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoria',
            name='tipo_accion',
            field=models.CharField(choices=[('CREAR_USUARIO', 'Crear Usuario'), ('EDITAR_ROL', 'Editar Rol de Usuario'), ('DESACTIVAR_USUARIO', 'Desactivar Usuario'), ('IMPORTACION', 'Importación de Datos'), ('CREAR_REGLA', 'Crear Regla'), ('MODIFICAR_REGLA', 'Modificar Regla'), ('ACTIVAR_REGLA', 'Activar Regla'), ('DESACTIVAR_REGLA', 'Desactivar Regla'), ('CERRAR_ALERTA', 'Cerrar Alerta'), ('REGISTRAR_INTERVENCION', 'Registrar Intervención'), ('CONCLUIR_INTERVENCION', 'Concluir Intervención'), ('GENERAR_ALERTAS', 'Generar Alertas'), ('LOGIN', 'Inicio de Sesión'), ('ACCESO_DENEGADO', 'Acceso Denegado (403)'), ('REGISTRO_ASISTENCIA', 'Registro de Asistencia'), ('ENVIO_RECORDATORIOS', 'Envío de Recordatorios'), ('CONFIGURAR_RECORDATORIOS', 'Configurar Recordatorios'), ('REEVALUAR_ALERTAS', 'Reevaluar Alertas'), ('RECALCULAR_RIESGO', 'Recalcular Riesgo de Estudiante'), ('REEVALUACION_RIESGO', 'Re-evaluación Periódica del Riesgo'), ('MIGRAR_RIESGO_PERIODOS', 'Migrar Riesgo por Periodos')], max_length=50),
        ),
    ]
