# Generated by Django 6.0.4 on 2026-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_auditoria_tipos_faltantes"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="contrasena_cambiada_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
