# Generated by Django 6.0.4 on 2026-04-13 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_vinculacion', models.CharField(choices=[('DOCENTE PLANTA', 'Docente Planta'), ('DOCENTE CATEDRA', 'Docente Cátedra')], max_length=30)),
                ('correo_personal', models.EmailField(blank=True, max_length=150, null=True)),
                ('correo_institucional', models.EmailField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.departamento')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('horario', models.CharField(blank=True, max_length=200, null=True)),
                ('num_matriculados', models.IntegerField(default=0)),
                ('creditos', models.IntegerField(blank=True, null=True)),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academico.docente')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(blank=True, choices=[('TI', 'Tarjeta de Identidad'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], max_length=5, null=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True)),
                ('anio_ingreso', models.IntegerField(blank=True, null=True)),
                ('semestre_ingreso', models.IntegerField(blank=True, null=True)),
                ('promedio_acumulado', models.FloatField(blank=True, null=True)),
                ('semestre_actual', models.IntegerField(blank=True, null=True)),
                ('pensum', models.IntegerField(blank=True, null=True)),
                ('estado_matricula', models.CharField(blank=True, choices=[('MATRICULADO', 'Matriculado'), ('LIQUIDADO', 'Liquidado'), ('ACTIVADO PARA LIQUIDACION', 'Activado para Liquidación'), ('CURSO DE VACACIONES', 'Curso de Vacaciones'), ('EXCLUIDO O INACTIVO', 'Excluido o Inactivo'), ('PENDIENTE POR PROCESAR', 'Pendiente por Procesar')], max_length=40, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('email_institucional', models.EmailField(blank=True, max_length=150, null=True)),
                ('colegio_egresado', models.CharField(blank=True, max_length=120, null=True)),
                ('municipio_nacimiento', models.CharField(blank=True, max_length=80, null=True)),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('semestre', models.IntegerField(choices=[(1, 'Primero'), (2, 'Segundo')])),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Período Académico',
                'verbose_name_plural': 'Períodos Académicos',
                'db_table': 'periodoacademico',
                'unique_together': {('anio', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('RETIRADO', 'Retirado'), ('CANCELADO', 'Cancelado'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado')], default='ACTIVO', max_length=30)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.curso')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'matricula',
                'unique_together': {('estudiante', 'curso', 'periodo')},
            },
        ),
    ]
