# Generated by Django 6.0.4 on 2026-04-16 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_documento', models.CharField(max_length=30)),
                ('numero_documento', models.CharField(max_length=30, unique=True)),
                ('semestre', models.SmallIntegerField()),
                ('pensum', models.CharField(blank=True, max_length=20, null=True)),
                ('ingreso', models.DateField(blank=True, null=True)),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('estado_matricula', models.CharField(max_length=30)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('email_personal', models.CharField(blank=True, max_length=150, null=True)),
                ('email_institucional', models.CharField(blank=True, max_length=150, null=True)),
                ('colegio_egresado', models.CharField(blank=True, max_length=200, null=True)),
                ('municipio_nacimiento', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'estudiante',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('creditos', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'materia',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo_vinculacion', models.CharField(max_length=50)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_institucional', models.CharField(blank=True, max_length=150, null=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='docente', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'docente',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.CharField(max_length=2)),
                ('horario', models.CharField(blank=True, max_length=200, null=True)),
                ('cantidad_matriculados', models.IntegerField(default=0)),
                ('docente', models.ForeignKey(db_column='codigo_docente', on_delete=django.db.models.deletion.PROTECT, to='academico.docente')),
                ('materia', models.ForeignKey(db_column='codigo_materia', on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'curso',
                'unique_together': {('materia', 'grupo')},
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('semestre', models.SmallIntegerField()),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'periodo',
                'unique_together': {('anio', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definitiva', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('estudiante', models.ForeignKey(db_column='codigo_estudiante', on_delete=django.db.models.deletion.CASCADE, to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodo')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'nota',
            },
        ),
    ]
