# Generated by Django 6.0.4 on 2026-04-27 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
        ('usuarios', '0001_initial'),
        ('alertas', '0002_delete_bitacoraimportacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('archivo_nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('total_procesados', models.IntegerField(default=0)),
                ('total_errores', models.IntegerField(default=0)),
                ('detalles_errores', models.JSONField(blank=True, default=list)),
                ('exitoso', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Bitácora de Importación',
                'verbose_name_plural': 'Bitácoras de Importación',
                'db_table': 'bitacora_importacion',
            },
        ),
    ]
