# Generated by Django 6.0.4 on 2026-04-15 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
