# Generated by Django 6.0.4 on 2026-05-14 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_bitacoraimportacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='semestre',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
