# Generated by Django 6.0.4 on 2026-05-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_materia_semestre'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='tipo',
            field=models.CharField(choices=[('linea', 'De línea'), ('profesional', 'Electiva Profesional'), ('sociohumanistica', 'Electiva Sociohumanística')], default='linea', max_length=20),
        ),
    ]
