# Generated by Django 6.0.4 on 2026-06-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_materia_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nota',
            unique_together={('estudiante', 'curso', 'periodo')},
        ),
    ]
