# Generated by Django 6.0.4 on 2026-06-02 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_nota_unique_estudiante_curso_periodo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquivalenciaMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia_equivalente', models.ForeignKey(help_text='Materia aprobada que satisface el requisito.', on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_salientes', to='academico.materia')),
                ('materia_pensum', models.ForeignKey(help_text='Materia del pensum que se considera cumplida.', on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_entrantes', to='academico.materia')),
            ],
            options={
                'verbose_name': 'Equivalencia de Materia',
                'verbose_name_plural': 'Equivalencias de Materias',
                'db_table': 'equivalencia_materia',
                'unique_together': {('materia_pensum', 'materia_equivalente')},
            },
        ),
    ]
