# Generated by Django 6.0.4 on 2026-09-29 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0006_equivalencia_materia'),
        ('usuarios', '0007_alter_auditoria_tipo_accion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_clase', models.DateField()),
                ('estado', models.CharField(choices=[('ASISTIO', 'Asistió'), ('FALTA', 'Falta'), ('FALTA_JUSTIFICADA', 'Falta justificada')], default='ASISTIO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.curso')),
                ('estudiante', models.ForeignKey(db_column='codigo_estudiante', on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.estudiante')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodo')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencia',
                'indexes': [models.Index(fields=['curso', 'periodo'], name='asistencia_curso_periodo_idx'), models.Index(fields=['estudiante', 'periodo'], name='asistencia_est_periodo_idx')],
                'unique_together': {('estudiante', 'curso', 'fecha_clase')},
            },
        ),
    ]
