# Generated by Django 6.0.4 on 2026-10-06 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0007_asistencia'),
        ('academico', '0007_nota_corte1_nota_corte2_nota_corte3_and_more'),
    ]

    operations = [
    ]
