# Generated by Django 6.0.4 on 2026-10-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0008_merge_asistencia_notas_cortes"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="observacion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
