# Generated by Django 6.0.4 on 2026-10-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academico", "0009_asistencia_observacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="curso",
            name="umbral_inasistencia",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
