"""
Django settings for alertas_tempranas_ufps project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Pruebas e2e (Playwright): base SQLite propia y sin el .env, para no tocar la base
# real ni enviar correos ni subir archivos a servicios externos
EJECUTANDO_E2E = os.environ.get('E2E') == 'True'

# Carga las variables del archivo .env
if not EJECUTANDO_E2E:
    load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

import sys
from django.core.exceptions import ImproperlyConfigured

EJECUTANDO_TESTS = 'test' in sys.argv

# Producción por defecto: el modo debug hay que activarlo explícitamente (DEBUG=True en .env)
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Con esta clave se firman los JWT y los enlaces de recuperación: en producción es obligatoria
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not (DEBUG or EJECUTANDO_TESTS):
        raise ImproperlyConfigured('Define la variable de entorno SECRET_KEY (obligatoria con DEBUG=False).')
    SECRET_KEY = 'django-insecure-solo-desarrollo-local'

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]

# Render proporciona automáticamente el hostname externo
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

if not ALLOWED_HOSTS:
    if not (DEBUG or EJECUTANDO_TESTS):
        raise ImproperlyConfigured('Define ALLOWED_HOSTS (o RENDER_EXTERNAL_HOSTNAME) con DEBUG=False.')
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # Apps del proyecto SAT
    'usuarios',
    'academico',
    'alertas',
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = DEBUG  # En producción, define CORS_ALLOWED_ORIGINS en .env

# Lista de orígenes permitidos en producción.
# Ejemplo en .env: CORS_ALLOWED_ORIGINS=https://tu-frontend.com,https://otro-origen.com
_cors_origins = os.environ.get('CORS_ALLOWED_ORIGINS', '')
if _cors_origins:
    CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins.split(',') if o.strip()]

ROOT_URLCONF = 'alertas_tempranas_ufps.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'alertas_tempranas_ufps.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True
        )
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME':     os.environ.get('DB_NAME'),
            'USER':     os.environ.get('DB_USER'),
            'PASSWORD': os.environ.get('DB_PASSWORD'),
            'HOST':     os.environ.get('DB_HOST'),
            'PORT':     os.environ.get('DB_PORT', '5432'),
            'OPTIONS': {
                'sslmode': 'require',
            },
        }
    }

# Usar SQLite para las pruebas automatizadas (evita problemas de permisos y es más rápido)
if EJECUTANDO_TESTS:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }

if EJECUTANDO_E2E:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db_e2e.sqlite3',
    }

# En los tests las tareas en segundo plano corren síncronas (ver alertas/tareas.py).
# En e2e también: así la pantalla ya ve el riesgo y las alertas al responder la importación.
TAREAS_EN_SEGUNDO_PLANO = not (EJECUTANDO_TESTS or EJECUTANDO_E2E)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# LOGGING
# ==============================================================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
    'loggers': {
        # Logs propios del proyecto: DEBUG en desarrollo, WARNING en producción
        'academico': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'alertas': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        'usuarios': {
            'handlers': ['console'],
            'level': 'DEBUG' if DEBUG else 'WARNING',
            'propagate': False,
        },
        # Silenciar logs muy verbosos de Django en producción
        'django.security': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

# Email configuration
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Alertas Tempranas UFPS <alertas-tempranas@ufps.edu.co>')

# URL del Frontend (ajustar según el entorno)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:5173')

# Tamaño máximo de archivos de importación en MB (por defecto 10 MB)
MAX_IMPORT_FILE_SIZE_MB = int(os.environ.get('MAX_IMPORT_FILE_SIZE_MB', 10))

# Si más de este porcentaje de registros de un archivo de estudiantes es inválido,
# la importación se cancela completa (INC-01)
IMPORT_MAX_PORCENTAJE_INVALIDOS = float(os.environ.get('IMPORT_MAX_PORCENTAJE_INVALIDOS', 10))

# Intentos fallidos de inicio de sesión por correo antes de bloquear temporalmente.
# El contador vive en la caché de Django (por defecto en memoria de cada proceso).
LOGIN_MAX_INTENTOS = int(os.environ.get('LOGIN_MAX_INTENTOS', 5))
LOGIN_BLOQUEO_MINUTOS = int(os.environ.get('LOGIN_BLOQUEO_MINUTOS', 15))

# ==============================================================================
# HU-29: RE-EVALUACIÓN PERIÓDICA DEL RIESGO
# ==============================================================================
# Token que debe enviar el programador externo (GitHub Actions / cron) en el
# header X-Cron-Token. Si no se define, el endpoint programado queda deshabilitado.
REEVALUACION_CRON_TOKEN = os.environ.get('REEVALUACION_CRON_TOKEN', '')
# Número máximo de intentos por ejecución (1 = sin reintentos)
REEVALUACION_MAX_INTENTOS = int(os.environ.get('REEVALUACION_MAX_INTENTOS', 3))
# Espera base entre reintentos, en segundos (se duplica en cada intento)
REEVALUACION_ESPERA_SEGUNDOS = int(os.environ.get('REEVALUACION_ESPERA_SEGUNDOS', 60))
# Una ejecución EN_CURSO más antigua que esto se considera abandonada y no bloquea
REEVALUACION_BLOQUEO_HORAS = int(os.environ.get('REEVALUACION_BLOQUEO_HORAS', 2))

# ==============================================================================
# HU-30: RECORDATORIOS DE ALERTAS E INTERVENCIONES SIN SEGUIMIENTO
# ==============================================================================
# Valores iniciales de ConfiguracionRecordatorio; luego se ajustan desde la API
# (GET/PUT /api/alertas/recordatorios/configuracion/).
RECORDATORIOS_DIAS_INACTIVIDAD_ALERTA = int(os.environ.get('RECORDATORIOS_DIAS_INACTIVIDAD_ALERTA', 7))
RECORDATORIOS_DIAS_INACTIVIDAD_INTERVENCION = int(os.environ.get('RECORDATORIOS_DIAS_INACTIVIDAD_INTERVENCION', 15))
RECORDATORIOS_DIAS_ENTRE_RECORDATORIOS = int(os.environ.get('RECORDATORIOS_DIAS_ENTRE_RECORDATORIOS', 7))
RECORDATORIOS_MAX_INTENTOS = int(os.environ.get('RECORDATORIOS_MAX_INTENTOS', 3))
RECORDATORIOS_ROLES_DESTINATARIOS = [
    r.strip().upper() for r in os.environ.get('RECORDATORIOS_ROLES_DESTINATARIOS', 'DIRECTOR').split(',') if r.strip()
]
# Una ejecución en curso más antigua que esto se considera abandonada y no bloquea
RECORDATORIOS_BLOQUEO_HORAS = int(os.environ.get('RECORDATORIOS_BLOQUEO_HORAS', 2))
# Token del programador externo (header X-Cron-Token). Por defecto, el mismo de la re-evaluación.
RECORDATORIOS_CRON_TOKEN = os.environ.get('RECORDATORIOS_CRON_TOKEN', REEVALUACION_CRON_TOKEN)
